preferred_syntax = :sass
http_path = '/'
css_dir = 'app/css'
sass_dir = 'app/scss'
images_dir = 'app/images'
javascripts_dir = 'app/scripts'
fonts_dir = 'app/fonts'
relative_assets = true
line_comments = true
# output_style = :compressed